name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-action@v2
        with:
          args: >
            -Dsonar.projectKey=jannik_jannik
            -Dsonar.organization=jannik
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
